name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '>=1.22' }
      - run: test -z "$(gofmt -l .)"
      - run: go build ./...
      - run: go test ./...
